// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * BackupInfo
 */
export type BackupInfo = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Size
     */
    size: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BackupResult
 */
export type BackupResult = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * Message
     */
    message: string;
};

/**
 * Body_restore_from_backup_file_backups_restore_post
 */
export type BodyRestoreFromBackupFileBackupsRestorePost = {
    /**
     * File
     *
     * Backup tar.gz file to restore from
     */
    file: Blob | File;
};

/**
 * ColumnDefinition
 *
 * Model for adding a new column to a table.
 */
export type ColumnDefinition = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Nullable
     */
    nullable?: boolean;
    /**
     * Default
     */
    default?: string | null;
};

/**
 * ColumnUpdate
 *
 * Model for updating column properties.
 */
export type ColumnUpdate = {
    /**
     * New Name
     */
    new_name?: string | null;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Nullable
     */
    nullable?: boolean | null;
    /**
     * Default
     */
    default?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RestoreResult
 */
export type RestoreResult = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * SystemStatus
 */
export type SystemStatus = {
    /**
     * Initialized
     */
    initialized: boolean;
    /**
     * Version
     */
    version: string;
};

/**
 * TableCreate
 */
export type TableCreate = {
    /**
     * Name
     *
     * Table name (lowercase letters, numbers, underscores, must start with letter)
     */
    name: string;
    /**
     * Schema
     *
     * JSON schema definition for table structure
     */
    schema: {
        [key: string]: unknown;
    };
    /**
     * Public
     */
    public?: boolean;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TableDataResponse
 *
 * Response model for table data with metadata.
 */
export type TableDataResponse = {
    /**
     * Data
     */
    data: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * TableRead
 */
export type TableRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Schema
     *
     * JSON schema definition for table structure
     */
    schema: {
        [key: string]: unknown;
    };
    /**
     * Public
     */
    public?: boolean;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Row Count
     */
    row_count?: number;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * TableUpdate
 */
export type TableUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Schema
     */
    schema?: {
        [key: string]: unknown;
    } | null;
    /**
     * Public
     */
    public?: boolean | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Lastname
     */
    lastName: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Lastname
     */
    lastName: string;
    role?: UserRole;
    /**
     * Isactive
     */
    isActive?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'USER' | 'ADMIN';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: null;
    role?: UserRole | null;
    /**
     * Isactive
     */
    isActive?: boolean | null;
    /**
     * Firstname
     */
    firstName?: string | null;
    /**
     * Lastname
     */
    lastName?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ErrorResponse
 */
export type EndpointsBackupsErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * UserCreate
 */
export type UserCreateWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdateWritable = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    role?: UserRole | null;
    /**
     * Isactive
     */
    isActive?: boolean | null;
    /**
     * Firstname
     */
    firstName?: string | null;
    /**
     * Lastname
     */
    lastName?: string | null;
};

export type LoginForAccessTokenUsersTokenPostData = {
    body: LoginRequest;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/users/token';
};

export type LoginForAccessTokenUsersTokenPostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenUsersTokenPostError = LoginForAccessTokenUsersTokenPostErrors[keyof LoginForAccessTokenUsersTokenPostErrors];

export type LoginForAccessTokenUsersTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenUsersTokenPostResponse = LoginForAccessTokenUsersTokenPostResponses[keyof LoginForAccessTokenUsersTokenPostResponses];

export type ReadUsersMeUsersMeGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUsersMeUsersMeGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
};

export type ReadUsersMeUsersMeGetError = ReadUsersMeUsersMeGetErrors[keyof ReadUsersMeUsersMeGetErrors];

export type ReadUsersMeUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUsersMeUsersMeGetResponse = ReadUsersMeUsersMeGetResponses[keyof ReadUsersMeUsersMeGetResponses];

export type GetUserCountUsersCountGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: {
        /**
         * Search
         *
         * Search term for filtering by email, first name, or last name
         */
        search?: string | null;
    };
    url: '/users/count';
};

export type GetUserCountUsersCountGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserCountUsersCountGetError = GetUserCountUsersCountGetErrors[keyof GetUserCountUsersCountGetErrors];

export type GetUserCountUsersCountGetResponses = {
    /**
     * Response Get User Count Users Count Get
     *
     * Successful Response
     */
    200: number;
};

export type GetUserCountUsersCountGetResponse = GetUserCountUsersCountGetResponses[keyof GetUserCountUsersCountGetResponses];

export type ReadUsersUsersGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         *
         * Search term for filtering by email, first name, or last name
         */
        search?: string | null;
        /**
         * Sort By
         *
         * Field to sort by
         */
        sort_by?: 'created_at' | 'email' | 'first_name' | 'last_name';
        /**
         * Sort Order
         *
         * Sort order (ascending or descending)
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/users/';
};

export type ReadUsersUsersGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersUsersGetError = ReadUsersUsersGetErrors[keyof ReadUsersUsersGetErrors];

export type ReadUsersUsersGetResponses = {
    /**
     * Response Read Users Users  Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type ReadUsersUsersGetResponse = ReadUsersUsersGetResponses[keyof ReadUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreateWritable;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserUsersPostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponses[keyof DeleteUserUsersUserIdDeleteResponses];

export type ReadUserUsersUserIdGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type ReadUserUsersUserIdGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserUsersUserIdGetError = ReadUserUsersUserIdGetErrors[keyof ReadUserUsersUserIdGetErrors];

export type ReadUserUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUserUsersUserIdGetResponse = ReadUserUsersUserIdGetResponses[keyof ReadUserUsersUserIdGetResponses];

export type UpdateUserUsersUserIdPatchData = {
    body: UserUpdateWritable;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPatchErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPatchError = UpdateUserUsersUserIdPatchErrors[keyof UpdateUserUsersUserIdPatchErrors];

export type UpdateUserUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserUsersUserIdPatchResponse = UpdateUserUsersUserIdPatchResponses[keyof UpdateUserUsersUserIdPatchResponses];

export type GetTableCountTablesCountGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: {
        /**
         * Search
         *
         * Search term for filtering by name or description
         */
        search?: string | null;
    };
    url: '/tables/count';
};

export type GetTableCountTablesCountGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTableCountTablesCountGetError = GetTableCountTablesCountGetErrors[keyof GetTableCountTablesCountGetErrors];

export type GetTableCountTablesCountGetResponses = {
    /**
     * Response Get Table Count Tables Count Get
     *
     * Successful Response
     */
    200: number;
};

export type GetTableCountTablesCountGetResponse = GetTableCountTablesCountGetResponses[keyof GetTableCountTablesCountGetResponses];

export type ReadTablesTablesGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         *
         * Search term for filtering by name or description
         */
        search?: string | null;
        /**
         * Sort By
         *
         * Field to sort by
         */
        sort_by?: 'created_at' | 'updated_at' | 'name';
        /**
         * Sort Order
         *
         * Sort order (ascending or descending)
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/tables/';
};

export type ReadTablesTablesGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTablesTablesGetError = ReadTablesTablesGetErrors[keyof ReadTablesTablesGetErrors];

export type ReadTablesTablesGetResponses = {
    /**
     * Response Read Tables Tables  Get
     *
     * Successful Response
     */
    200: Array<TableRead>;
};

export type ReadTablesTablesGetResponse = ReadTablesTablesGetResponses[keyof ReadTablesTablesGetResponses];

export type CreateTableTablesPostData = {
    body: TableCreate;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/tables/';
};

export type CreateTableTablesPostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTableTablesPostError = CreateTableTablesPostErrors[keyof CreateTableTablesPostErrors];

export type CreateTableTablesPostResponses = {
    /**
     * Successful Response
     */
    201: TableRead;
};

export type CreateTableTablesPostResponse = CreateTableTablesPostResponses[keyof CreateTableTablesPostResponses];

export type DeleteTableTablesTableIdDeleteData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
    };
    query?: never;
    url: '/tables/{table_id}';
};

export type DeleteTableTablesTableIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTableTablesTableIdDeleteError = DeleteTableTablesTableIdDeleteErrors[keyof DeleteTableTablesTableIdDeleteErrors];

export type DeleteTableTablesTableIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTableTablesTableIdDeleteResponse = DeleteTableTablesTableIdDeleteResponses[keyof DeleteTableTablesTableIdDeleteResponses];

export type ReadTableTablesTableIdGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
    };
    query?: never;
    url: '/tables/{table_id}';
};

export type ReadTableTablesTableIdGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTableTablesTableIdGetError = ReadTableTablesTableIdGetErrors[keyof ReadTableTablesTableIdGetErrors];

export type ReadTableTablesTableIdGetResponses = {
    /**
     * Successful Response
     */
    200: TableRead;
};

export type ReadTableTablesTableIdGetResponse = ReadTableTablesTableIdGetResponses[keyof ReadTableTablesTableIdGetResponses];

export type UpdateTableTablesTableIdPatchData = {
    body: TableUpdate;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
    };
    query?: never;
    url: '/tables/{table_id}';
};

export type UpdateTableTablesTableIdPatchErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTableTablesTableIdPatchError = UpdateTableTablesTableIdPatchErrors[keyof UpdateTableTablesTableIdPatchErrors];

export type UpdateTableTablesTableIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TableRead;
};

export type UpdateTableTablesTableIdPatchResponse = UpdateTableTablesTableIdPatchResponses[keyof UpdateTableTablesTableIdPatchResponses];

export type AddColumnTablesTableIdColumnsPostData = {
    body: ColumnDefinition;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
    };
    query?: never;
    url: '/tables/{table_id}/columns';
};

export type AddColumnTablesTableIdColumnsPostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddColumnTablesTableIdColumnsPostError = AddColumnTablesTableIdColumnsPostErrors[keyof AddColumnTablesTableIdColumnsPostErrors];

export type AddColumnTablesTableIdColumnsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteColumnTablesTableIdColumnsColumnNameDeleteData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
        /**
         * Column Name
         */
        column_name: string;
    };
    query?: never;
    url: '/tables/{table_id}/columns/{column_name}';
};

export type DeleteColumnTablesTableIdColumnsColumnNameDeleteErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteColumnTablesTableIdColumnsColumnNameDeleteError = DeleteColumnTablesTableIdColumnsColumnNameDeleteErrors[keyof DeleteColumnTablesTableIdColumnsColumnNameDeleteErrors];

export type DeleteColumnTablesTableIdColumnsColumnNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateColumnTablesTableIdColumnsColumnNamePatchData = {
    body: ColumnUpdate;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
        /**
         * Column Name
         */
        column_name: string;
    };
    query?: never;
    url: '/tables/{table_id}/columns/{column_name}';
};

export type UpdateColumnTablesTableIdColumnsColumnNamePatchErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateColumnTablesTableIdColumnsColumnNamePatchError = UpdateColumnTablesTableIdColumnsColumnNamePatchErrors[keyof UpdateColumnTablesTableIdColumnsColumnNamePatchErrors];

export type UpdateColumnTablesTableIdColumnsColumnNamePatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTableDataTablesTableIdDataGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Search
         *
         * Search term for filtering across all text columns
         */
        search?: string | null;
        /**
         * Sort By
         *
         * Column name to sort by
         */
        sort_by?: string | null;
        /**
         * Sort Order
         *
         * Sort order (ascending or descending)
         */
        sort_order?: 'asc' | 'desc';
    };
    url: '/tables/{table_id}/data';
};

export type GetTableDataTablesTableIdDataGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTableDataTablesTableIdDataGetError = GetTableDataTablesTableIdDataGetErrors[keyof GetTableDataTablesTableIdDataGetErrors];

export type GetTableDataTablesTableIdDataGetResponses = {
    /**
     * Successful Response
     */
    200: TableDataResponse;
};

export type GetTableDataTablesTableIdDataGetResponse = GetTableDataTablesTableIdDataGetResponses[keyof GetTableDataTablesTableIdDataGetResponses];

export type InsertRowTablesTableIdDataPostData = {
    /**
     * Row Data
     */
    body: {
        [key: string]: unknown;
    };
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
    };
    query?: never;
    url: '/tables/{table_id}/data';
};

export type InsertRowTablesTableIdDataPostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InsertRowTablesTableIdDataPostError = InsertRowTablesTableIdDataPostErrors[keyof InsertRowTablesTableIdDataPostErrors];

export type InsertRowTablesTableIdDataPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteRowTablesTableIdDataRowIdDeleteData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
        /**
         * Row Id
         */
        row_id: string;
    };
    query?: {
        /**
         * Id Column
         */
        id_column?: string;
    };
    url: '/tables/{table_id}/data/{row_id}';
};

export type DeleteRowTablesTableIdDataRowIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRowTablesTableIdDataRowIdDeleteError = DeleteRowTablesTableIdDataRowIdDeleteErrors[keyof DeleteRowTablesTableIdDataRowIdDeleteErrors];

export type DeleteRowTablesTableIdDataRowIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRowTablesTableIdDataRowIdDeleteResponse = DeleteRowTablesTableIdDataRowIdDeleteResponses[keyof DeleteRowTablesTableIdDataRowIdDeleteResponses];

export type UpdateRowTablesTableIdDataRowIdPatchData = {
    /**
     * Updates
     */
    body: {
        [key: string]: unknown;
    };
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Table Id
         */
        table_id: string;
        /**
         * Row Id
         */
        row_id: string;
    };
    query?: {
        /**
         * Id Column
         */
        id_column?: string;
    };
    url: '/tables/{table_id}/data/{row_id}';
};

export type UpdateRowTablesTableIdDataRowIdPatchErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Conflict
     */
    409: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRowTablesTableIdDataRowIdPatchError = UpdateRowTablesTableIdDataRowIdPatchErrors[keyof UpdateRowTablesTableIdDataRowIdPatchErrors];

export type UpdateRowTablesTableIdDataRowIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSystemStatusSystemStatusGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/system/status';
};

export type GetSystemStatusSystemStatusGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
};

export type GetSystemStatusSystemStatusGetError = GetSystemStatusSystemStatusGetErrors[keyof GetSystemStatusSystemStatusGetErrors];

export type GetSystemStatusSystemStatusGetResponses = {
    /**
     * Successful Response
     */
    200: SystemStatus;
};

export type GetSystemStatusSystemStatusGetResponse = GetSystemStatusSystemStatusGetResponses[keyof GetSystemStatusSystemStatusGetResponses];

export type ListAllBackupsBackupsGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/backups';
};

export type ListAllBackupsBackupsGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
};

export type ListAllBackupsBackupsGetError = ListAllBackupsBackupsGetErrors[keyof ListAllBackupsBackupsGetErrors];

export type ListAllBackupsBackupsGetResponses = {
    /**
     * Response List All Backups Backups Get
     *
     * Successful Response
     */
    200: Array<BackupInfo>;
};

export type ListAllBackupsBackupsGetResponse = ListAllBackupsBackupsGetResponses[keyof ListAllBackupsBackupsGetResponses];

export type CreateNewBackupBackupsPostData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/backups';
};

export type CreateNewBackupBackupsPostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
};

export type CreateNewBackupBackupsPostError = CreateNewBackupBackupsPostErrors[keyof CreateNewBackupBackupsPostErrors];

export type CreateNewBackupBackupsPostResponses = {
    /**
     * Successful Response
     */
    200: BackupResult;
};

export type CreateNewBackupBackupsPostResponse = CreateNewBackupBackupsPostResponses[keyof CreateNewBackupBackupsPostResponses];

export type DownloadBackupBackupsFilenameDownloadGetData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/backups/{filename}/download';
};

export type DownloadBackupBackupsFilenameDownloadGetErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadBackupBackupsFilenameDownloadGetError = DownloadBackupBackupsFilenameDownloadGetErrors[keyof DownloadBackupBackupsFilenameDownloadGetErrors];

export type DownloadBackupBackupsFilenameDownloadGetResponses = {
    /**
     * Backup file download
     */
    200: unknown;
};

export type DeleteBackupFileBackupsFilenameDeleteData = {
    body?: never;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/backups/{filename}';
};

export type DeleteBackupFileBackupsFilenameDeleteErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * Forbidden
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBackupFileBackupsFilenameDeleteError = DeleteBackupFileBackupsFilenameDeleteErrors[keyof DeleteBackupFileBackupsFilenameDeleteErrors];

export type DeleteBackupFileBackupsFilenameDeleteResponses = {
    /**
     * Response Delete Backup File Backups  Filename  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteBackupFileBackupsFilenameDeleteResponse = DeleteBackupFileBackupsFilenameDeleteResponses[keyof DeleteBackupFileBackupsFilenameDeleteResponses];

export type RestoreFromBackupFileBackupsRestorePostData = {
    body: BodyRestoreFromBackupFileBackupsRestorePost;
    headers: {
        /**
         * API key required for all endpoints (validated by middleware)
         */
        'X-API-Key': string;
    };
    path?: never;
    query?: never;
    url: '/backups/restore';
};

export type RestoreFromBackupFileBackupsRestorePostErrors = {
    /**
     * Bad Request
     */
    400: EndpointsBackupsErrorResponse;
    /**
     * Unauthorized
     */
    401: EndpointsBackupsErrorResponse;
    /**
     * System already initialized
     */
    403: EndpointsBackupsErrorResponse;
    /**
     * Not Found
     */
    404: EndpointsBackupsErrorResponse;
    /**
     * Method Not Allowed
     */
    405: EndpointsBackupsErrorResponse;
    /**
     * Not Acceptable
     */
    406: EndpointsBackupsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestoreFromBackupFileBackupsRestorePostError = RestoreFromBackupFileBackupsRestorePostErrors[keyof RestoreFromBackupFileBackupsRestorePostErrors];

export type RestoreFromBackupFileBackupsRestorePostResponses = {
    /**
     * Successful Response
     */
    200: RestoreResult;
};

export type RestoreFromBackupFileBackupsRestorePostResponse = RestoreFromBackupFileBackupsRestorePostResponses[keyof RestoreFromBackupFileBackupsRestorePostResponses];
